In [1]:
import numpy as np

## Method 1: Array creation from python list and tuples

In [2]:
arr = np.array([1, 127, 3], np.int8)

In [3]:
arr

array([  1, 127,   3], dtype=int8)

In [4]:
arr.shape

(3,)

In [5]:
arr.dtype

dtype('int8')

## Method 2: Array creation from intrinsic numpy objects

### This creates an array of zeros

In [6]:
zeros = np.zeros((3, 4))

In [7]:
zeros.shape

(3, 4)

In [8]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### This creates an array starting from 0 till num - 1, works same as python range function

In [9]:
rng = np.arange(20)

In [10]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### This creates an array from start till end and contains x elements and all elements are equally spaced

In [11]:
lspace = np.linspace(0, 50, 8)

In [12]:
lspace

array([ 0.        ,  7.14285714, 14.28571429, 21.42857143, 28.57142857,
       35.71428571, 42.85714286, 50.        ])

### This creates an array of give size populated with random elements

In [13]:
emp = np.empty((4, 5))

In [14]:
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### This creates an array having the same structure(size and dimension) populated with random elements

In [15]:
emp_like = np.empty_like(rng)

In [16]:
emp_like

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### This creates an identity array

In [17]:
ide = np.identity(5)

In [18]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Axis in numpy array

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 0, 1]])

In [20]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

*Note: In 2-D array row is along the axis 0 while columns are along the axis 1*

In [21]:
x.sum(axis = 0)

array([12,  7, 10])

In [22]:
x.sum(axis = 1)

array([ 6, 15,  8])

### Array Attributes

In [23]:
# For transpose
x.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [24]:
# For traversing an array: flat gives an iterator
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [25]:
# For getting the dimension
x.ndim

2

In [26]:
# For size
x.size

9

In [27]:
# For getting the space occupied in bytes
x.nbytes

72

### Array Fucntions

In [28]:
reshaped = np.arange(10).reshape(5, 2)

In [29]:
reshaped

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
# To flatten an array
reshaped.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
reshaped

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
demo = np.array([1, 4, 2, 6, 9, 7, 3])

In [33]:
# For getting the max element index
demo.argmax()

np.int64(4)

In [34]:
# Provides sorted order through indices
demo.argsort()

array([0, 2, 6, 1, 3, 5, 4])

In [35]:
# For getting the min element index
demo.argmin()

np.int64(0)

In [36]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [37]:
x.argmin(axis = 0)

array([0, 2, 2])

In [38]:
x.argmax(axis=1)

array([2, 2, 0])

In [39]:
x.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

### Matrix operations in numpy

In [40]:
m1 = np.array([[1, 2, 1], [0, 0, 0], [4, 3, 5]])

In [41]:
m2 = np.array([[1, 1, 1], [0, 0, 0], [2, 3, 2]])

In [42]:
m1 

array([[1, 2, 1],
       [0, 0, 0],
       [4, 3, 5]])

In [43]:
m2

array([[1, 1, 1],
       [0, 0, 0],
       [2, 3, 2]])

In [44]:
# Note: These operations are performed on elements at same posistions
m1 + m2

array([[2, 3, 2],
       [0, 0, 0],
       [6, 6, 7]])

In [45]:
m1 * m2

array([[ 1,  2,  1],
       [ 0,  0,  0],
       [ 8,  9, 10]])

In [46]:
np.sqrt(m1)

array([[1.        , 1.41421356, 1.        ],
       [0.        , 0.        , 0.        ],
       [2.        , 1.73205081, 2.23606798]])

In [47]:
m1

array([[1, 2, 1],
       [0, 0, 0],
       [4, 3, 5]])

In [48]:
m1.sum()

np.int64(16)

In [49]:
m1.max()

np.int64(5)

In [50]:
m1.min()

np.int64(0)

In [51]:
m1.sum(axis=1)

array([ 4,  0, 12])

In [52]:
# This will return the row and column index where the conditions are true
np.where(m1 > 1)

(array([0, 2, 2, 2]), array([1, 0, 1, 2]))

In [53]:
m1[np.where(m1 > 1)]

array([2, 4, 3, 5])

In [54]:
np.count_nonzero(m1)

np.int64(6)

In [55]:
np.nonzero(m1)

(array([0, 0, 0, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

### Proof numpy takes less space

In [56]:
import sys

In [57]:
py_arr = [1, 3, 4, 5]

In [58]:
np_arr = np.array(py_arr)

In [59]:
sys.getsizeof(1) * len(py_arr)

112

In [60]:
np_arr.itemsize * np_arr.size

32

### Numpy arrays are faster than python arrays 

In [61]:
import time

In [62]:
a = list(range(1000000))
b = np.array(a)

start = time.time()
[x*2 for x in a]
print("Python List time:", time.time() - start)

start = time.time()
b*2
print("NumPy array time:", time.time() - start)

Python List time: 0.0334467887878418
NumPy array time: 0.0015690326690673828
